package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer questionId;
	private java.lang.String answerValue;

	private java.lang.String questionType;

	private java.lang.String questionPrompt;

	@org.kie.api.definition.type.Label("Sequence")
	private java.lang.Integer questionOrder;

	@org.kie.api.definition.type.Label("Question Level")
	private java.lang.Integer questionLevel;

	@org.kie.api.definition.type.Label(value = "Drop Down List Options")
	private java.lang.String listOptions;

	public AdditionalInformation() {
	}

	public java.lang.Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(java.lang.Integer questionId) {
		this.questionId = questionId;
	}

	public java.lang.String getAnswerValue() {
		return this.answerValue;
	}

	public void setAnswerValue(java.lang.String answerValue) {
		this.answerValue = answerValue;
	}

	public java.lang.String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(java.lang.String questionType) {
		this.questionType = questionType;
	}

	public java.lang.String getQuestionPrompt() {
		return this.questionPrompt;
	}

	public void setQuestionPrompt(java.lang.String questionPrompt) {
		this.questionPrompt = questionPrompt;
	}

	public java.lang.Integer getQuestionOrder() {
		return this.questionOrder;
	}

	public void setQuestionOrder(java.lang.Integer questionOrder) {
		this.questionOrder = questionOrder;
	}

	public java.lang.Integer getQuestionLevel() {
		return this.questionLevel;
	}

	public void setQuestionLevel(java.lang.Integer questionLevel) {
		this.questionLevel = questionLevel;
	}

	public java.lang.String getListOptions() {
		return this.listOptions;
	}

	public void setListOptions(java.lang.String listOptions) {
		this.listOptions = listOptions;
	}

	public AdditionalInformation(java.lang.Integer questionId,
			java.lang.String answerValue, java.lang.String questionType,
			java.lang.String questionPrompt, java.lang.Integer questionOrder,
			java.lang.Integer questionLevel, java.lang.String listOptions) {
		this.questionId = questionId;
		this.answerValue = answerValue;
		this.questionType = questionType;
		this.questionPrompt = questionPrompt;
		this.questionOrder = questionOrder;
		this.questionLevel = questionLevel;
		this.listOptions = listOptions;
	}

}