package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer lineItemCount;
	private java.lang.Integer maxDaysElapsed;

	private java.lang.Float totalFraudAmount;

	private boolean automated;

	private java.lang.String customerStatus;

	private java.lang.String cardType;

	private java.lang.String customerUse;

	private java.lang.String issueType;

	private java.lang.String agentPriority;

	public FraudData() {
	}

	public java.lang.Integer getLineItemCount() {
		return this.lineItemCount;
	}

	public void setLineItemCount(java.lang.Integer lineItemCount) {
		this.lineItemCount = lineItemCount;
	}

	public java.lang.Integer getMaxDaysElapsed() {
		return this.maxDaysElapsed;
	}

	public void setMaxDaysElapsed(java.lang.Integer maxDaysElapsed) {
		this.maxDaysElapsed = maxDaysElapsed;
	}

	public FraudData(java.lang.Float totalFraudAmount,
			java.lang.Integer lineItemCount, java.lang.Integer maxDaysElapsed,
			boolean automated, java.lang.String customerStatus) {
		this.totalFraudAmount = totalFraudAmount;
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
		this.automated = automated;
		this.customerStatus = customerStatus;
	}

	public java.lang.Float getTotalFraudAmount() {
		return this.totalFraudAmount;
	}

	public void setTotalFraudAmount(java.lang.Float totalFraudAmount) {
		this.totalFraudAmount = totalFraudAmount;
	}

	public boolean isAutomated() {
		return this.automated;
	}

	public void setAutomated(boolean automated) {
		this.automated = automated;
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public java.lang.String getCardType() {
		return this.cardType;
	}

	public void setCardType(java.lang.String cardType) {
		this.cardType = cardType;
	}

	public java.lang.String getCustomerUse() {
		return this.customerUse;
	}

	public void setCustomerUse(java.lang.String customerUse) {
		this.customerUse = customerUse;
	}

	public java.lang.String getIssueType() {
		return this.issueType;
	}

	public void setIssueType(java.lang.String issueType) {
		this.issueType = issueType;
	}

	public java.lang.String getAgentPriority() {
		return this.agentPriority;
	}

	public void setAgentPriority(java.lang.String agentPriority) {
		this.agentPriority = agentPriority;
	}

	public FraudData(java.lang.Integer lineItemCount,
			java.lang.Integer maxDaysElapsed, java.lang.Float totalFraudAmount,
			boolean automated, java.lang.String customerStatus,
			java.lang.String cardType, java.lang.String customerUse,
			java.lang.String issueType, java.lang.String agentPriority) {
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
		this.totalFraudAmount = totalFraudAmount;
		this.automated = automated;
		this.customerStatus = customerStatus;
		this.cardType = cardType;
		this.customerUse = customerUse;
		this.issueType = issueType;
		this.agentPriority = agentPriority;
	}

}