package com.fsi.creditcarddisputecase;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleFiredIds implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String ruleFiredIds;

	public RuleFiredIds() {
	}

	public java.lang.String getRuleFiredIds() {
		return this.ruleFiredIds;
	}

	public void setRuleFiredIds(java.lang.String ruleFiredIds) {
		this.ruleFiredIds = ruleFiredIds;
	}

	public RuleFiredIds(java.lang.String ruleFiredIds) {
		this.ruleFiredIds = ruleFiredIds;
	}

}