package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String userId;
	private java.lang.String userName;
	private Boolean fraudInvestigation;
	private Boolean premiumCardSupport;
	private java.lang.Boolean mutliCardTypeSupport;
	private java.lang.Boolean coBrandCardSupport;

	private java.lang.Boolean german;

	private java.lang.Boolean french;

	public UserInfo() {
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public java.lang.Boolean getMutliCardTypeSupport() {
		return this.mutliCardTypeSupport;
	}

	public void setMutliCardTypeSupport(java.lang.Boolean mutliCardTypeSupport) {
		this.mutliCardTypeSupport = mutliCardTypeSupport;
	}

	public java.lang.Boolean getCoBrandCardSupport() {
		return this.coBrandCardSupport;
	}

	public void setCoBrandCardSupport(java.lang.Boolean coBrandCardSupport) {
		this.coBrandCardSupport = coBrandCardSupport;
	}

	public java.lang.Boolean getGerman() {
		return this.german;
	}

	public void setGerman(java.lang.Boolean german) {
		this.german = german;
	}

	public java.lang.Boolean getFrench() {
		return this.french;
	}

	public void setFrench(java.lang.Boolean french) {
		this.french = french;
	}

	public java.lang.Boolean getPremiumCardSupport() {
		return this.premiumCardSupport;
	}

	public void setPremiumCardSupport(java.lang.Boolean premiumCardSupport) {
		this.premiumCardSupport = premiumCardSupport;
	}

	public java.lang.Boolean getFraudInvestigation() {
		return this.fraudInvestigation;
	}

	public void setFraudInvestigation(java.lang.Boolean fraudInvestigation) {
		this.fraudInvestigation = fraudInvestigation;
	}

	public UserInfo(java.lang.String userId, java.lang.String userName,
			java.lang.Boolean fraudInvestigation,
			java.lang.Boolean premiumCardSupport,
			java.lang.Boolean mutliCardTypeSupport,
			java.lang.Boolean coBrandCardSupport, java.lang.Boolean german,
			java.lang.Boolean french) {
		this.userId = userId;
		this.userName = userName;
		this.fraudInvestigation = fraudInvestigation;
		this.premiumCardSupport = premiumCardSupport;
		this.mutliCardTypeSupport = mutliCardTypeSupport;
		this.coBrandCardSupport = coBrandCardSupport;
		this.german = german;
		this.french = french;
	}

}