package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkQueue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String workQueueName;
	public WorkQueue() {
	}

	public java.lang.String getWorkQueueName() {
		return this.workQueueName;
	}

	public void setWorkQueueName(java.lang.String workQueueName) {
		this.workQueueName = workQueueName;
	}

	public WorkQueue(java.lang.String workQueueName) {
		this.workQueueName = workQueueName;
	}

}